name: Build V2Ray rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 */3 * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "LICENSE*"
      - "*.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Dat Files Release" >> $GITHUB_ENV
          echo "TAG_NAME=dat-release" >> $GITHUB_ENV

          echo "GEOIP_URL=https://raw.githubusercontent.com/sweep7125/geoip/release/geoip.dat" >> $GITHUB_ENV
          echo "GEOSITE_URL=https://raw.githubusercontent.com/sweep7125/geosite/release/geosite.dat" >> $GITHUB_ENV
        shell: bash

      - name: Checkout runetfreedom/geodat2srs
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/geodat2srs
          path: geodat2srs
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geodat2srs/go.mod
          cache-dependency-path: ./geodat2srs/go.sum

      - name: Collect files
        run: |
          mkdir -p ./publish
          curl -sSL $GEOIP_URL > ./publish/geoip.dat
          curl -sSL $GEOIP_URL.sha256sum > ./publish/geoip.dat.sha256sum

          curl -sSL $GEOSITE_URL > ./publish/geosite.dat
          curl -sSL $GEOSITE_URL.sha256sum > ./publish/geosite.dat.sha256sum

      - name: Generate sing-box srs
        run: |
          go build -C geodat2srs ./
          ./geodat2srs/geodat2srs geoip -i ./publish/geoip.dat -o ./tmp/sing-box/rule-set-geoip/
          ./geodat2srs/geodat2srs geosite -i ./publish/geosite.dat -o ./tmp/sing-box/rule-set-geosite/
          cd ./tmp/sing-box || exit 1
          zip -r ../../publish/sing-box.zip *

      - name: Git push assets to "release" branch
        run: |
          rm -rf ./publish/sing-box.zip
          mv ./tmp/sing-box ./publish/sing-box
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Create or update release and upload top-level assets
        run: |
          if ! gh release view "${{ env.TAG_NAME }}" > /dev/null 2>&1; then
            gh release create "${{ env.TAG_NAME }}" -t "${{ env.RELEASE_NAME }}" -n "Release generated automatically" --target release --draft=false
          fi
          gh release upload "${{ env.TAG_NAME }}" $(find ./publish -maxdepth 1 -type f) --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


